# Etapa 1: construir el frontend con Node
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: servir el build con Nginx
FROM nginx:stable
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
