version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_control
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 110968Lucas
      MYSQL_DATABASE: shastino
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./controlProductos
    container_name: backend_control
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shastino
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 110968Lucas
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend_control
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
